const db = require('../db');

const allowedBillEntities = ['OPD_VISIT', 'LAB', 'IPD_ADMISSION', 'OT_CASE', 'ICU_STAY', 'PHARMACY'];
const allowedStatus = ['Active', 'Inactive'];

const mapBillEntityRow = (row) => ({
  BillEntityId: row.BillEntityId || row.billentityid,
  BillEntity: row.BillEntity || row.billentity,
  EntityDescription: row.EntityDescription || row.entitydescription || null,
  Status: row.Status || row.status,
  BillEntityCreatedBy: row.BillEntityCreatedBy || row.billentitycreatedby || null,
  BillEntityCreatedAt: row.BillEntityCreatedAt || row.billentitycreatedat,
  CreatedByUserName: row.UserName || row.username || null,
});

exports.getAllBillEntities = async (req, res) => {
  try {
    const { status, billEntity } = req.query;
    let query = `
      SELECT be.*, u."UserName"
      FROM "BillEntity" be
      LEFT JOIN "Users" u ON be."BillEntityCreatedBy" = u."UserId"
    `;
    const params = [];
    const conditions = [];

    if (status) {
      conditions.push(`be."Status" = $${params.length + 1}`);
      params.push(status);
    }
    if (billEntity) {
      conditions.push(`be."BillEntity" = $${params.length + 1}`);
      params.push(billEntity);
    }

    if (conditions.length > 0) {
      query += ' WHERE ' + conditions.join(' AND ');
    }
    query += ' ORDER BY be."BillEntityCreatedAt" DESC';

    const { rows } = await db.query(query, params);
    res.status(200).json({
      success: true,
      count: rows.length,
      data: rows.map(mapBillEntityRow),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching bill entities',
      error: error.message,
    });
  }
};

exports.getBillEntityById = async (req, res) => {
  try {
    const { id } = req.params;
    const billEntityId = parseInt(id, 10);
    if (isNaN(billEntityId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid BillEntityId. Must be an integer.' 
      });
    }
    const { rows } = await db.query(
      `
      SELECT be.*, u."UserName"
      FROM "BillEntity" be
      LEFT JOIN "Users" u ON be."BillEntityCreatedBy" = u."UserId"
      WHERE be."BillEntityId" = $1
      `,
      [billEntityId]
    );
    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Bill entity not found' });
    }
    res.status(200).json({ success: true, data: mapBillEntityRow(rows[0]) });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching bill entity',
      error: error.message,
    });
  }
};

exports.getBillEntitiesByType = async (req, res) => {
  try {
    const { billEntity } = req.params;
    
    if (!billEntity || !billEntity.trim()) {
      return res.status(400).json({ 
        success: false, 
        message: 'BillEntity type is required' 
      });
    }

    const { rows } = await db.query(
      `
      SELECT be.*, u."UserName"
      FROM "BillEntity" be
      LEFT JOIN "Users" u ON be."BillEntityCreatedBy" = u."UserId"
      WHERE be."BillEntity" = $1
      ORDER BY be."BillEntityCreatedAt" DESC
      `,
      [billEntity.trim()]
    );
    
    res.status(200).json({ 
      success: true,
      count: rows.length,
      billEntity: billEntity.trim(),
      data: rows.map(mapBillEntityRow)
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching bill entities by type',
      error: error.message,
    });
  }
};

const validateBillEntityPayload = (body, requireAll = true) => {
  const errors = [];
  
  if (requireAll && (!body.BillEntity || !body.BillEntity.trim())) {
    errors.push('BillEntity is required');
  }
  
  if (body.BillEntity && !allowedBillEntities.includes(body.BillEntity.trim())) {
    errors.push(`BillEntity must be one of: ${allowedBillEntities.join(', ')}`);
  }
  
  if (body.Status && !allowedStatus.includes(body.Status)) {
    errors.push('Status must be Active or Inactive');
  }
  
  return errors;
};

exports.createBillEntity = async (req, res) => {
  try {
    const errors = validateBillEntityPayload(req.body, true);
    if (errors.length > 0) {
      return res.status(400).json({ success: false, message: errors.join(', ') });
    }

    const {
      BillEntity,
      EntityDescription,
      Status = 'Active',
      BillEntityCreatedBy,
    } = req.body;

    // Validate BillEntityCreatedBy if provided - must be a valid integer
    let createdByValue = null;
    if (BillEntityCreatedBy !== undefined && BillEntityCreatedBy !== null && BillEntityCreatedBy !== '') {
      const createdByInt = parseInt(BillEntityCreatedBy, 10);
      if (isNaN(createdByInt)) {
        return res.status(400).json({ 
          success: false, 
          message: 'BillEntityCreatedBy must be a valid integer. Leave it empty or null if not needed.' 
        });
      }
      createdByValue = createdByInt;
    }

    // BillEntityId is auto-generated by PostgreSQL SERIAL, so we don't include it in INSERT
    const insertQuery = `
      INSERT INTO "BillEntity"
        ("BillEntity", "EntityDescription", "Status", "BillEntityCreatedBy")
      VALUES ($1, $2, $3, $4)
      RETURNING *;
    `;

    const { rows } = await db.query(insertQuery, [
      BillEntity.trim(),
      EntityDescription ? EntityDescription.trim() : null,
      Status,
      createdByValue,
    ]);

    // Fetch with user name
    const { rows: newRows } = await db.query(
      `
      SELECT be.*, u."UserName"
      FROM "BillEntity" be
      LEFT JOIN "Users" u ON be."BillEntityCreatedBy" = u."UserId"
      WHERE be."BillEntityId" = $1
      `,
      [rows[0].BillEntityId]
    );

    res.status(201).json({
      success: true,
      message: 'Bill entity created successfully',
      data: mapBillEntityRow(newRows[0]),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error creating bill entity',
      error: error.message,
    });
  }
};

exports.updateBillEntity = async (req, res) => {
  try {
    const errors = validateBillEntityPayload(req.body, false);
    if (errors.length > 0) {
      return res.status(400).json({ success: false, message: errors.join(', ') });
    }

    const { id } = req.params;
    const billEntityId = parseInt(id, 10);
    if (isNaN(billEntityId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid BillEntityId. Must be an integer.' 
      });
    }

    const {
      BillEntity,
      EntityDescription,
      Status,
      BillEntityCreatedBy,
    } = req.body;

    // Validate BillEntityCreatedBy if provided - must be a valid integer
    let createdByValue = null;
    if (BillEntityCreatedBy !== undefined && BillEntityCreatedBy !== null && BillEntityCreatedBy !== '') {
      const createdByInt = parseInt(BillEntityCreatedBy, 10);
      if (isNaN(createdByInt)) {
        return res.status(400).json({ 
          success: false, 
          message: 'BillEntityCreatedBy must be a valid integer. Leave it empty or null if not needed.' 
        });
      }
      createdByValue = createdByInt;
    }

    const updateQuery = `
      UPDATE "BillEntity"
      SET
        "BillEntity" = COALESCE($1, "BillEntity"),
        "EntityDescription" = COALESCE($2, "EntityDescription"),
        "Status" = COALESCE($3, "Status"),
        "BillEntityCreatedBy" = COALESCE($4, "BillEntityCreatedBy")
      WHERE "BillEntityId" = $5
      RETURNING *;
    `;

    const { rows } = await db.query(updateQuery, [
      BillEntity ? BillEntity.trim() : null,
      EntityDescription ? EntityDescription.trim() : null,
      Status || null,
      createdByValue || null,
      billEntityId,
    ]);

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Bill entity not found' });
    }

    // Fetch with user name
    const { rows: updatedRows } = await db.query(
      `
      SELECT be.*, u."UserName"
      FROM "BillEntity" be
      LEFT JOIN "Users" u ON be."BillEntityCreatedBy" = u."UserId"
      WHERE be."BillEntityId" = $1
      `,
      [billEntityId]
    );

    res.status(200).json({
      success: true,
      message: 'Bill entity updated successfully',
      data: mapBillEntityRow(updatedRows[0]),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error updating bill entity',
      error: error.message,
    });
  }
};

exports.deleteBillEntity = async (req, res) => {
  try {
    const { id } = req.params;
    const billEntityId = parseInt(id, 10);
    if (isNaN(billEntityId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid BillEntityId. Must be an integer.' 
      });
    }
    const { rows } = await db.query(
      'DELETE FROM "BillEntity" WHERE "BillEntityId" = $1 RETURNING *;',
      [billEntityId]
    );
    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Bill entity not found' });
    }

    res.status(200).json({
      success: true,
      message: 'Bill entity deleted successfully',
      data: mapBillEntityRow(rows[0]),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error deleting bill entity',
      error: error.message,
    });
  }
};

