const db = require('../db');

const mapDepartmentRow = (row) => ({
  DoctorDepartmentId: row.DoctorDepartmentId || row.doctordepartmentid,
  DepartmentName: row.DepartmentName || row.departmentname,
  DepartmentCategory: row.DepartmentCategory || row.departmentcategory,
  SpecialisationDetails: row.SpecialisationDetails || row.specialisationdetails,
  NoOfDoctors: row.NoOfDoctors || row.noofdoctors || 0,
  Status: row.Status || row.status,
  CreatedAt: row.CreatedAt || row.createdat,
  CreatedBy: row.CreatedBy || row.createdby,
});

exports.getAllDepartments = async (req, res) => {
  try {
    const { status } = req.query;
    let query = 'SELECT * FROM "DoctorDepartment"';
    const params = [];
    if (status) {
      query += ' WHERE "Status" = $1';
      params.push(status);
    }
    query += ' ORDER BY "CreatedAt" DESC';

    const { rows } = await db.query(query, params);
    res.status(200).json({
      success: true,
      count: rows.length,
      data: rows.map(mapDepartmentRow),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching doctor departments',
      error: error.message,
    });
  }
};

exports.getDepartmentById = async (req, res) => {
  try {
    const { id } = req.params;
    // Validate that id is an integer
    const deptId = parseInt(id, 10);
    if (isNaN(deptId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid DoctorDepartmentId. Must be an integer.' 
      });
    }
    const { rows } = await db.query(
      'SELECT * FROM "DoctorDepartment" WHERE "DoctorDepartmentId" = $1',
      [deptId]
    );
    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Department not found' });
    }
    res.status(200).json({ success: true, data: mapDepartmentRow(rows[0]) });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching department',
      error: error.message,
    });
  }
};

exports.createDepartment = async (req, res) => {
  try {
    const { DepartmentName, DepartmentCategory, SpecialisationDetails, NoOfDoctors, Status = 'Active', CreatedBy } = req.body;
    if (!DepartmentName || !DepartmentName.trim()) {
      return res
        .status(400)
        .json({ success: false, message: 'DepartmentName is required' });
    }

    // Validate DepartmentCategory if provided
    const allowedCategories = ['Clinical', 'Surgical', 'Diagnostic', 'Critical Care', 'Support'];
    let departmentCategoryValue = null;
    if (DepartmentCategory !== undefined && DepartmentCategory !== null && DepartmentCategory !== '') {
      const trimmedCategory = typeof DepartmentCategory === 'string' ? DepartmentCategory.trim() : String(DepartmentCategory).trim();
      if (trimmedCategory !== '') {
        if (!allowedCategories.includes(trimmedCategory)) {
          return res.status(400).json({ 
            success: false, 
            message: `DepartmentCategory must be one of: ${allowedCategories.join(', ')}.` 
          });
        }
        departmentCategoryValue = trimmedCategory;
      }
    }

    const trimmedDepartmentName = DepartmentName.trim();

    // Check if DepartmentName already exists (proactive validation)
    const checkQuery = 'SELECT "DoctorDepartmentId", "DepartmentName" FROM "DoctorDepartment" WHERE LOWER("DepartmentName") = LOWER($1)';
    const { rows: existingDepartments } = await db.query(checkQuery, [trimmedDepartmentName]);
    
    if (existingDepartments.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Department with name "${trimmedDepartmentName}" already exists. DepartmentName must be unique.`,
        error: 'DUPLICATE_DEPARTMENT_NAME',
      });
    }

    // Validate CreatedBy if provided - must be a valid integer
    let createdByValue = null;
    if (CreatedBy !== undefined && CreatedBy !== null && CreatedBy !== '') {
      const createdByInt = parseInt(CreatedBy, 10);
      if (isNaN(createdByInt)) {
        return res.status(400).json({ 
          success: false, 
          message: 'CreatedBy must be a valid integer. Leave it empty or null if not needed.' 
        });
      }
      createdByValue = createdByInt;
    }

    // DoctorDepartmentId is auto-generated by PostgreSQL SERIAL, so we don't include it in INSERT
    const insertQuery = `
      INSERT INTO "DoctorDepartment" ("DepartmentName", "DepartmentCategory", "SpecialisationDetails", "NoOfDoctors", "Status", "CreatedBy")
      VALUES ($1, $2, $3, $4, $5, $6)
      RETURNING *;
    `;

    const params = [
      trimmedDepartmentName,
      departmentCategoryValue,
      SpecialisationDetails ? SpecialisationDetails.trim() : null,
      NoOfDoctors || 0,
      Status,
      createdByValue,
    ];

    const { rows } = await db.query(insertQuery, params);

    res.status(201).json({
      success: true,
      message: 'Department created successfully',
      data: mapDepartmentRow(rows[0]),
    });
  } catch (error) {
    if (error.code === '23505') {
      // Unique constraint violation - DepartmentName already exists (fallback check)
      if (error.message && error.message.includes('DepartmentName')) {
        return res.status(400).json({
          success: false,
          message: `Department with name "${DepartmentName}" already exists. DepartmentName must be unique.`,
          error: 'DUPLICATE_DEPARTMENT_NAME',
        });
      }
      return res.status(400).json({
        success: false,
        message: 'A department with this information already exists. Please try again.',
        error: error.message,
      });
    }
    // Handle invalid integer format error
    if (error.message && (error.message.includes('invalid input syntax for type integer') || error.message.includes('invalid input syntax for type numeric'))) {
      return res.status(400).json({
        success: false,
        message: 'CreatedBy must be a valid integer. Leave it empty or null if not needed.',
        error: error.message,
      });
    }
    res.status(500).json({
      success: false,
      message: 'Error creating department',
      error: error.message,
    });
  }
};

exports.updateDepartment = async (req, res) => {
  try {
    const { id } = req.params;
    // Validate that id is an integer
    const deptId = parseInt(id, 10);
    if (isNaN(deptId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid DoctorDepartmentId. Must be an integer.' 
      });
    }
    const { DepartmentName, DepartmentCategory, SpecialisationDetails, NoOfDoctors, Status } = req.body;

    // Validate DepartmentCategory if provided
    const allowedCategories = ['Clinical', 'Surgical', 'Diagnostic', 'Critical Care', 'Support'];
    let departmentCategoryValue = null;
    if (DepartmentCategory !== undefined && DepartmentCategory !== null && DepartmentCategory !== '') {
      const trimmedCategory = typeof DepartmentCategory === 'string' ? DepartmentCategory.trim() : String(DepartmentCategory).trim();
      if (trimmedCategory !== '') {
        if (!allowedCategories.includes(trimmedCategory)) {
          return res.status(400).json({ 
            success: false, 
            message: `DepartmentCategory must be one of: ${allowedCategories.join(', ')}.` 
          });
        }
        departmentCategoryValue = trimmedCategory;
      }
    }

    // If DepartmentName is being updated, check if it already exists for another department
    if (DepartmentName && DepartmentName.trim()) {
      const trimmedDepartmentName = DepartmentName.trim();
      
      // Check if DepartmentName already exists for a different department
      const checkQuery = 'SELECT "DoctorDepartmentId", "DepartmentName" FROM "DoctorDepartment" WHERE LOWER("DepartmentName") = LOWER($1) AND "DoctorDepartmentId" != $2';
      const { rows: existingDepartments } = await db.query(checkQuery, [trimmedDepartmentName, deptId]);
      
      if (existingDepartments.length > 0) {
        return res.status(400).json({
          success: false,
          message: `Department with name "${trimmedDepartmentName}" already exists. DepartmentName must be unique.`,
          error: 'DUPLICATE_DEPARTMENT_NAME',
        });
      }
    }

    const updateQuery = `
      UPDATE "DoctorDepartment"
      SET
        "DepartmentName" = COALESCE($1, "DepartmentName"),
        "DepartmentCategory" = COALESCE($2, "DepartmentCategory"),
        "SpecialisationDetails" = COALESCE($3, "SpecialisationDetails"),
        "NoOfDoctors" = COALESCE($4, "NoOfDoctors"),
        "Status" = COALESCE($5, "Status")
      WHERE "DoctorDepartmentId" = $6
      RETURNING *;
    `;

    const { rows } = await db.query(updateQuery, [
      DepartmentName ? DepartmentName.trim() : null,
      departmentCategoryValue,
      SpecialisationDetails ? SpecialisationDetails.trim() : null,
      NoOfDoctors !== undefined ? NoOfDoctors : null,
      Status || null,
      deptId,
    ]);

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Department not found' });
    }

    res.status(200).json({
      success: true,
      message: 'Department updated successfully',
      data: mapDepartmentRow(rows[0]),
    });
  } catch (error) {
    // Handle unique constraint violation for DepartmentName (fallback check)
    if (error.code === '23505') {
      if (error.message && error.message.includes('DepartmentName')) {
        return res.status(400).json({
          success: false,
          message: `Department with name "${DepartmentName}" already exists. DepartmentName must be unique.`,
          error: 'DUPLICATE_DEPARTMENT_NAME',
        });
      }
      return res.status(400).json({
        success: false,
        message: 'A department with this information already exists.',
        error: error.message,
      });
    }
    res.status(500).json({
      success: false,
      message: 'Error updating department',
      error: error.message,
    });
  }
};

exports.deleteDepartment = async (req, res) => {
  try {
    const { id } = req.params;
    // Validate that id is an integer
    const deptId = parseInt(id, 10);
    if (isNaN(deptId)) {
      return res.status(400).json({ 
        success: false, 
        message: 'Invalid DoctorDepartmentId. Must be an integer.' 
      });
    }
    const { rows } = await db.query(
      'DELETE FROM "DoctorDepartment" WHERE "DoctorDepartmentId" = $1 RETURNING *;',
      [deptId]
    );
    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: 'Department not found' });
    }
    res.status(200).json({
      success: true,
      message: 'Department deleted successfully',
      data: mapDepartmentRow(rows[0]),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error deleting department',
      error: error.message,
    });
  }
};

